# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 06:50
from __future__ import unicode_literals

from django.db import migrations
import form_designer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form_designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='mail_reply_to',
            field=form_designer.fields.TemplateCharField(blank=True, help_text='Your form fields are available as template context. Example: "{{ first_name }} {{ last_name }} <{{ from_email }}>" if you have fields named `first_name`, `last_name`, `from_email`.', max_length=255, verbose_name='reply-to address'),
        ),
    ]
